CREATE TABLE MOTORISTA(
IDMOTORISTA INT PRIMARY KEY AUTO_INCREMENT
NOME VARCHAR(30) NOT NULL,
NASCIMENTO VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(100),
TIPOCNH CHAR(2) NOT NULL,
NUMCNH VARCHAR(20) NOT NULL,
);

CREATE TABLE OBJETO(
IDOBJETO INT PRIMARY KEY AUTO_INCREMENT
NOMEREM VARCHAR(30),
ENDERECOREM VARCHAR(30),
NOMEDEST VARCHAR(30),
ENDERECODEST VARCHAR(30),
DATADEP DATE,
PESO FLOAT(30)

CREATE TABLE VEICULOS(
IDVEICULO INT PRIMARY KEY AUTO_INCREMENT
