CREATE TABLE MOTORISTA(
IDMOTORISTA INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
NASCIMENTO VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(100),
TIPOCNH CHAR(2) NOT NULL,
NUMCNH VARCHAR(20) NOT NULL
);

CREATE TABLE OBJETO(
IDOBJETO INT PRIMARY KEY AUTO_INCREMENT,
NOMEREM VARCHAR(30),
ENDERECOREM VARCHAR(30),
NOMEDEST VARCHAR(30),
ENDERECODEST VARCHAR(30),
DATADEP DATE,
PESO FLOAT(30),
/*ID_VEICULO INT,
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(IDVEICULO)*/
);

CREATE TABLE VEICULO(
IDVEICULO INT PRIMARY KEY AUTO_INCREMENT,
MARCA VARCHAR(20),
MODELO VARCHAR(30),
ANO INT(4),
PLACA CHAR(7),
TIPO VARCHAR(20),
CARGAMAX INT (2)
);

CREATE TABLE ROTEIRO(
IDROTEIRO INT PRIMARY KEY NOT NULL,
DATAR DATE,
ID_MOTORISTA INT,
ID_OBJETO INT,
ID_VEICULO INT,
FOREIGN KEY (ID_MOTORISTA) REFERENCES MOTORISTA(IDMOTORISTA),
FOREIGN KEY (ID_OBJETO) REFERENCES OBJETO(IDOBJETO),
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(IDVEICULO)
);

SELECT IDMOTORISTA, IDVEICULO, IDOBJETO
FROM MOTORISTA
