CREATE TABLE MOTORISTA(
IDMOTORISTA INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
NASCIMENTO VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(100),
TIPOCNH CHAR(2) NOT NULL,
NUMCNH VARCHAR(20) NOT NULL
);

CREATE TABLE OBJETO(
IDOBJETO INT PRIMARY KEY AUTO_INCREMENT,
NOMEREM VARCHAR(30),
ENDERECOREM VARCHAR(30),
NOMEDEST VARCHAR(30),
ENDERECODEST VARCHAR(30),
DATADEP DATE,
PESO FLOAT(30),
/*ID_VEICULO INT,
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(IDVEICULO)*/
);

CREATE TABLE VEICULO(
IDVEICULO INT PRIMARY KEY AUTO_INCREMENT,
MARCA VARCHAR(20),
MODELO VARCHAR(30),
ANO INT(4),
PLACA CHAR(7),
TIPO VARCHAR(20),
CARGAMAX INT (2)
);

CREATE TABLE ROTEIROLISTA(
IDROTEIROLISTA INT PRIMARY KEY AUTO_INCREMENT,
ID_ROTEIRODATA INT,
ID_MOTORISTA INT,
ID_OBJETO INT,
ID_VEICULO INT,
FOREIGN KEY (ID_ROTEIRODATA) REFERENCES ROTEIRODATA(IDROTEIRODATA) ON DELETE SET NULL,
FOREIGN KEY (ID_MOTORISTA) REFERENCES MOTORISTA(IDMOTORISTA) ON DELETE SET NULL,
FOREIGN KEY (ID_OBJETO) REFERENCES OBJETO(IDOBJETO) ON DELETE SET NULL,
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(IDVEICULO) ON DELETE SET NULL
);

CREATE TABLE ROTEIRODATA(
IDROTEIRODATA INT PRIMARY KEY AUTO_INCREMENT,
DATAR DATE
);